---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webmain
  template:
    metadata:
      labels:
        app: webmain
    spec:
      containers:
        - image: hyunkyoungkang/busan-tour-kube:latest
          name: web-container
          ports:
            - containerPort: 8080
--- # 서비스
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: webmain
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080

